*&---------------------------------------------------------------------*
*& Include          ZDKTJ_WORKPLAN_ALV_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF SCREEN 1004 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-A01.
    PARAMETERS : P_MCODE TYPE ZTJ_WORKPLAN-MITEMCODE MATCHCODE OBJECT ZSH_ITEM_TEAM1
                 MODIF ID CM1.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT (56) TEXT-S01.
    SELECTION-SCREEN END OF LINE.

*    SELECTION-SCREEN BEGIN OF LINE.
*      SELECTION-SCREEN COMMENT (54) TEXT-S02.
*    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK BLOCK1.
SELECTION-SCREEN END OF SCREEN 1004.
