*&---------------------------------------------------------------------*
*& Include          ZDKTJ_BOM_TOP
*&---------------------------------------------------------------------*

CONTROLS TC100 TYPE TABLEVIEW USING SCREEN 100.

DATA : OK_CODE TYPE SY-UCOMM,
       SAVE_OK TYPE SY-UCOMM. "버튼클릭 저장

DATA : BEGIN OF GS_BOM,
        PLANTCODE TYPE ZTJ_BOM-PLANTCODE,
        MITEMCODE TYPE ZTJ_BOM-MITEMCODE,
        ITEMCODE TYPE ZTJ_BOM-ITEMCODE,
        COMPONENT TYPE ZTJ_BOM-COMPONENT,
        UOM TYPE ZTJ_BOM-UOM,
        QUANTITY TYPE ZTJ_BOM-QUANTITY,
       END OF GS_BOM,
       GT_BOM LIKE TABLE OF GS_BOM.

DATA : LV_ITEMNAME LIKE ZTJ_ITEM-COMPONENT.
DATA : LV_PLANTNAME LIKE ZTJ_RESMAP-RESNAME.
