*&---------------------------------------------------------------------*
*& Include          ZDKTJ_WORKPLAN_ALV_TOP
*&---------------------------------------------------------------------*
TABLES : ZTJ_WORKPLAN.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_FCAT TYPE LVC_S_FCAT,
       GT_FCAT TYPE LVC_T_FCAT.

DATA : BEGIN OF GS_WORKPL,
        PLAN_CODE TYPE ZTJ_WORKPLAN-PLAN_CODE,
        MITEMCODE TYPE ZTJ_WORKPLAN-MITEMCODE,
        COMPONENT TYPE ZTJ_WORKPLAN-COMPONENT,
        ICNAME TYPE ZTJ_WORKPLAN-ICNAME,
        PLAN_DATE TYPE ZTJ_WORKPLAN-PLAN_DATE,
        PLAN_QT TYPE ZTJ_WORKPLAN-PLAN_QT,
        PLAN_CONFIRM TYPE ZTJ_WORKPLAN-PLAN_CONFIRM,
        STYLE TYPE LVC_T_STYL,
        ZDELETE,
       END OF GS_WORKPL,
       GT_WORKPL LIKE TABLE OF GS_WORKPL.

DATA : GT_TOTSTOCK LIKE TABLE OF ZTJ_TOTSTOCK WITH HEADER LINE.
DATA : GT_TOTSTOCK2 LIKE TABLE OF ZTJ_TOTSTOCK WITH HEADER LINE.
DATA : GT_ITEM LIKE TABLE OF ZTJ_ITEM WITH HEADER LINE.
DATA : GT_BOM LIKE TABLE OF ZTJ_BOM WITH HEADER LINE.

DATA : LV_COMPONENT TYPE ZTJ_ITEM-COMPONENT.

DATA : GT_ZTJ_WORKPL LIKE TABLE OF ZTJ_WORKPLAN WITH HEADER LINE.

DATA : P_MCODE2(10).

DATA : GT_INDEX TYPE LVC_T_ROW, "ALV 선택라인 저장 인터널테이블
       GS_INDEX LIKE LINE OF GT_INDEX, "ALV 선택라인 저장 스트럭쳐
       GD_LINES TYPE I. "선택한 라인수를 저장할 변수

DATA : GS_STYLE TYPE LVC_S_STYL.
DATA : GS_LAYOUT TYPE LVC_S_LAYO.
