*&---------------------------------------------------------------------*
*& Include          ZDKTJ_ALV_TOP
*&---------------------------------------------------------------------*

DATA : OK_CODE TYPE SY-UCOMM,
       SAVE_OK TYPE SY-UCOMM.

DATA : BEGIN OF GS_BOM,
        MITEMCODE TYPE ZTJ_BOM-MITEMCODE,
        ITEMCDOE TYPE ZTJ_BOM-ITEMCODE,
        COMPONENT TYPE ZTJ_BOM-COMPONENT,
        UOM TYPE ZTJ_BOM-UOM,
       END OF GS_BOM,
       GT_BOM LIKE TABLE OF GS_BOM.

DATA : BEGIN OF GS_BOMROUT,
        MITEMCODE TYPE ZTJ_BOMROUTING-MITEMCODE,
        ITEMCODE TYPE ZTJ_BOMROUTING-ITEMCODE,
        STEP_NO TYPE ZTJ_BOMROUTING-STEP_NO,
        OP_NO TYPE ZTJ_BOMROUTING-OP_NO,
        ASS_CODE TYPE ZTJ_BOMROUTING-ASS_CODE,
       END OF GS_BOMROUT,
       GT_BOMROUT LIKE TABLE OF GS_BOMROUT.

DATA : BEGIN OF GS_WORKPL,
        MITEMCODE TYPE ZTJ_WORKPLAN-MITEMCODE,
        COMPONENT TYPE ZTJ_WORKPLAN-COMPONENT,
        ICNAME TYPE ZTJ_WORKPLAN-ICNAME,
        PLAN_DATE TYPE ZTJ_WORKPLAN-PLAN_DATE,
        PLAN_QT TYPE ZTJ_WORKPLAN-PLAN_QT,
        PLAN_CONFIRM TYPE ZTJ_WORKPLAN-PLAN_CONFIRM,
       END OF GS_WORKPL,
       GT_WORKPL LIKE TABLE OF GS_WORKPL.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : GC_CONTAINER TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_FCAT TYPE LVC_S_FCAT,
       GT_FCAT TYPE LVC_T_FCAT.
