*&---------------------------------------------------------------------*
*& Include          ZDKTJ_WORKPLAN_ALV_TOP
*&---------------------------------------------------------------------*
TABLES : ZTJ_WORKPLAN.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_FCAT TYPE LVC_S_FCAT,
       GT_FCAT TYPE LVC_T_FCAT.

DATA : BEGIN OF GS_WORKPL,
        PLAN_CODE TYPE ZTJ_WORKPLAN-PLAN_CODE,
        MITEMCODE TYPE ZTJ_WORKPLAN-MITEMCODE,
        COMPONENT TYPE ZTJ_WORKPLAN-COMPONENT,
        ICNAME TYPE ZTJ_WORKPLAN-ICNAME,
        PLAN_DATE TYPE ZTJ_WORKPLAN-PLAN_DATE,
        PLAN_QT TYPE ZTJ_WORKPLAN-PLAN_QT,
        PLAN_CONFIRM TYPE ZTJ_WORKPLAN-PLAN_CONFIRM,
        CHK,
        ZDELETE,
       END OF GS_WORKPL,
       GT_WORKPL LIKE TABLE OF GS_WORKPL.

*DATA : LV_MITEMCODE TYPE ZTJ_ITEM-ITEM_CODE.
DATA : LV_COMPONENT TYPE ZTJ_ITEM-COMPONENT.

DATA : GT_ZTJ_WORKPL LIKE TABLE OF ZTJ_WORKPLAN WITH HEADER LINE.

DATA : P_MCODE2(10).
