*&---------------------------------------------------------------------*
*& Include          ZDLDH_STOCK_TOP
*&---------------------------------------------------------------------*

TABLES : ZTJ_STOCK, ZTJ_ITEM, ZTJ_TOTSTOCK.

DATA : OK_CODE TYPE SY-UCOMM.
DATA : SAVE_OK TYPE SY-UCOMM.

DATA : BEGIN OF GS_STOCK,
        MANDT LIKE ZTJ_STOCK-MANDT,
        RTIME LIKE ZTJ_STOCK-RTIME,
        ITEM_CODE LIKE ZTJ_STOCK-ITEM_CODE,
        COMPONENT LIKE ZTJ_STOCK-COMPONENT,
        INQT LIKE ZTJ_STOCK-INQT,
        OUTQT LIKE ZTJ_STOCK-OUTQT,
        TOTALQT LIKE ZTJ_STOCK-TOTALQT,
      END OF GS_STOCK.
DATA : GT_STOCK LIKE TABLE OF GS_STOCK.

DATA : LV_RTIME LIKE ZTJ_STOCK-RTIME.

CONTROLS TC100 TYPE TABLEVIEW USING SCREEN 100.

DATA : LS_STOCK LIKE GS_STOCK.
DATA : LV_INPUT LIKE GS_STOCK-TOTALQT.


DATA : BEGIN OF GS_TOT,
        WAREID LIKE ZTJ_TOTSTOCK-WAREID,
        ITEM_CODE LIKE ZTJ_TOTSTOCK-ITEM_CODE,
        COMPONENT LIKE ZTJ_TOTSTOCK-COMPONENT,
        TOTALQT LIKE ZTJ_TOTSTOCK-TOTALQT,
       END OF GS_TOT.
DATA : GT_TOT LIKE TABLE OF GS_TOT.
