*&---------------------------------------------------------------------*
*& Report ZDLDH_TOTSTOCK_ALV
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDLDH_TOTSTOCK_ALV.

INCLUDE ZDLDH_TOTSTOCK_CLS.
INCLUDE ZDLDH_TOTSTOCK_TOP.
INCLUDE ZDLDH_TOTSTOCK_SEL.
INCLUDE ZDLDH_TOTSTOCK_PBO.
INCLUDE ZDLDH_TOTSTOCK_PAI.
INCLUDE ZDLDH_TOTSTOCK_F01.

INITIALIZATION.

START-OF-SELECTION.

*SELECT *
*  FROM ZTJ_TOTSTOCK
*  INTO CORRESPONDING FIELDS OF TABLE GT_DATA
*  WHERE ITEM_CODE IN S_ICODE.

"창고 코드 BOM에서 가져오도록 함
SELECT BOM~PLANTCODE AS WAREID, TOT~ITEM_CODE, TOT~COMPONENT, TOT~TOTALQT
  FROM ZTJ_TOTSTOCK AS TOT
  JOIN ZTJ_BOM AS BOM
  ON TOT~ITEM_CODE = BOM~ITEMCODE
  OR TOT~ITEM_CODE = BOM~MITEMCODE
  INTO CORRESPONDING FIELDS OF TABLE @GT_DATA
  WHERE ITEM_CODE IN @S_ICODE.

SORT GT_DATA BY WAREID ITEM_CODE TOTALQT.

DELETE ADJACENT DUPLICATES FROM GT_DATA COMPARING WAREID ITEM_CODE TOTALQT.

CALL SCREEN 100.
